#!/bin/sh
# /etc/init.d/scripts
# Description: Starts Python scripts
# ————————————————–
#
### BEGIN INIT INFO
# Provides: Scripts
# Required-Start: $network $local_fs $syslog
# Required-Stop: $local_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: Start Python script
### END INIT INFO

case $1 in
  start)
echo -n "Starting flashing service:"
~/RPiRFID/flash.py
;;
  stop)
echo -n "Stopping service:"
echo -n "TO DO"
;;
  restart)
echo -n "Retarting service:"
echo -n "TO DO"
;;
  *)
# echo "Usage: scripts {start|stop|restart}"
exit 1
esac

